# Uncomment the next line to define a global platform for your project
flutter_application_path = '/home/egor/Documents/flutter/comfort_confy'
#load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for Runner
  pod 'Firebase/Core'

end